### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by PhamZung26** [lamnguyenkhoa/container-code-recognition#2]
I have error:
"IndexError: invalid index to scalar variable."
![image](https://user-images.githubusercontent.com/37917861/159406595-d4857e95-31e7-47b3-bf8a-5ed21a0b0276.png)

How to fix it. Thanks

**Comment by lamnguyenkhoa** [comment]
It's maybe because your OpenCV version does not support CUDA, which means net.getUnconnectedOutLayers() will return a 1-D array instead of 2-D. You can see this discussion for more info: https://stackoverflow.com/questions/69834335/loading-yolo-invalid-index-to-scalar-variable/69881065

Meanwhile, can you replace line 32 with this to see if it work:
```
output_layers = [layer_names[i - 1] for i in net.getUnconnectedOutLayers()]
```

**Comment by PhamZung26** [comment]
Thanks, it worked. But with the vertical numbers, this program doesn't detect the region including numbers. If you want data to train it, I can provide it.
![image](https://user-images.githubusercontent.com/37917861/159678759-f7aa2b04-db7b-4400-90f0-3007832cee97.png)

**Comment by lamnguyenkhoa** [comment]
Thanks, but I'm not working on it anymore, so you have to train it yourself.
